events {}

http {
    upstream todo_service {
        server todo-service:5000;
    }

    upstream stats_service {
        server stats-service:5001;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://todo_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /stats {
            proxy_pass http://stats_service/stats;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}