events {}

http {
    upstream todo_service {
        server mini-projet-cloud-todo-service-1:5000;
        server mini-projet-cloud-todo-service-2:5000;
        server mini-projet-cloud-todo-service-3:5000;
    }

    upstream stats_service {
        server mini-projet-cloud-stats-service-1:5001;
    }

    server {
        listen 80;
        return 301 https://localhost:8443$request_uri;
    }

    server {
        listen 443 ssl;
        ssl_certificate /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        location / {
            proxy_pass http://todo_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /stats {
            proxy_pass http://stats_service/stats;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}